flutter_native_splash:
  color: "#19235a"
  image: "assets/images/ownerchip_infineon/app_logo_splash.png"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ownerchip/app_logo_splash.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  image_path_ios: "assets/images/ownerchip/app_logo_splash.png"
  remove_alpha_ios: true