// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfIDs5SgUhrFI36LKPDznJHXMattiPdCg',
    appId: '1:768172302210:web:e74f000c2def1f3a9d799b',
    messagingSenderId: '768172302210',
    projectId: 'test-oc-app-1f1c0',
    authDomain: 'test-oc-app-1f1c0.firebaseapp.com',
    storageBucket: 'test-oc-app-1f1c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6wp2Hr2qzaQbfcBeTwDuV-rg4SgEWTE',
    appId: '1:768172302210:android:e8170e1309a8f5989d799b',
    messagingSenderId: '768172302210',
    projectId: 'test-oc-app-1f1c0',
    storageBucket: 'test-oc-app-1f1c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuW8rS0-Pc-5DVyKAFREF29A7pD2habfA',
    appId: '1:768172302210:ios:a002fea6e852df769d799b',
    messagingSenderId: '768172302210',
    projectId: 'test-oc-app-1f1c0',
    storageBucket: 'test-oc-app-1f1c0.appspot.com',
    iosBundleId: 'com.ownerchip.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuW8rS0-Pc-5DVyKAFREF29A7pD2habfA',
    appId: '1:768172302210:ios:21f5d46f64074eae9d799b',
    messagingSenderId: '768172302210',
    projectId: 'test-oc-app-1f1c0',
    storageBucket: 'test-oc-app-1f1c0.appspot.com',
    iosBundleId: 'com.ownerchip.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfIDs5SgUhrFI36LKPDznJHXMattiPdCg',
    appId: '1:768172302210:web:960db0dc49e89d059d799b',
    messagingSenderId: '768172302210',
    projectId: 'test-oc-app-1f1c0',
    authDomain: 'test-oc-app-1f1c0.firebaseapp.com',
    storageBucket: 'test-oc-app-1f1c0.appspot.com',
  );
}
